process = require('process');
let number1 = parseInt(process.argv[2]);
let number2 = parseInt(process.argv[3]);
let number3 = parseInt(process.argv[4]);
let operation1 = number1 + number2 * number3;
let operation2 = number3 + number1 / number2;
let operation3 = number1 % number2 + number3;
let operation4 = number1 * number2 + number3;
console.log("a+b*c: " + operation1 + " c+a/b: " + operation2 + " a%b+c: " + operation3 + " a*b+c: " + operation4);
let maximum = Math.max(operation1, operation2, operation3, operation4);
let minimum = Math.min(operation1, operation2, operation3, operation4);
console.log("Maximum: " + maximum);
console.log("Minimum: " + minimum);